# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-20 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Debate Ended'),
        ),
    ]
