# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
