# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 23:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160819_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 23, 49, 23, 982033, tzinfo=utc), verbose_name=b'date published'),
            preserve_default=False,
        ),
    ]
