# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-20 01:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160819_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='team',
        ),
        migrations.AddField(
            model_name='page',
            name='mission',
            field=models.CharField(default=datetime.datetime(2016, 8, 20, 1, 26, 37, 643269, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='service',
            field=froala_editor.fields.FroalaField(default=datetime.datetime(2016, 8, 20, 1, 26, 53, 7263, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='vission',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
