# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-20 02:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20160820_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundRaisingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('service', froala_editor.fields.FroalaField()),
                ('location', models.CharField(max_length=500)),
                ('Ammounttoraise', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Date of Events')),
            ],
        ),
        migrations.CreateModel(
            name='PowerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('held_time', models.DateTimeField(verbose_name=b'Date of event')),
            ],
        ),
    ]
