# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160818_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_diplomat',
            field=models.BooleanField(default=False),
        ),
    ]
